TASK_TYPE: inference_dreamvideo_entrance
use_fp16: False
guide_scale: 9.0
chunk_size: 1
decoder_bs: 1
max_frames: 32
scale: 8
batch_size: 1
noise_strength: 0.1
round: 1
seed: 2767
use_random_seed: False
log_dir: workspace/dreamvideo/infer/subject_phantom_15
test_list_path: data/custom/infer/subject_phantom_15.txt
test_data_dir: /lustre/fs1/home/sr849057/Phantom-Data/phantom_sets/phantom_15
subject_cfg: configs/dreamvideo/subjectLearning/phantom15_step2.yaml
base_model: models/model_scope_v1-5_0632000.pth
text_embedding_path: workspace/dreamvideo/phantom15/step1/phantom15_step1/embeddings/text_embedding_of_*_0003000.pth
identity_adapter_path: workspace/dreamvideo/phantom15/step2/phantom15_step2/checkpoints/adapter_00000500.pth
